import { defineStore } from 'pinia';
import { ref, computed } from 'vue';

export const useGamesStore = defineStore('games', () => {
  const games = ref([
    {
      _id: 'g1',
      creator_id: '63b2a2d45f7c6c1a4b5e4b6f',
      title: 'Trivia Challenge',
      maxUsers: 5,
      category: 'trivia',
      game_code: 10101,
      question_ids: ['q1', 'q2', 'q3'],
      is_active: true,
    },
    {
      _id: 'g2',
      creator_id: '63b2a2d45f7c6c1a4b5e4b60',
      title: 'Math Battle',
      maxUsers: 4,
      category: 'math',
      game_code: 20202,
      question_ids: ['q4', 'q5'],
      is_active: true,
    },
    {
      _id: 'g3',
      creator_id: '63b2a2d45f7c6c1a4b5e4b61',
      title: 'Quick Quiz',
      maxUsers: 3,
      category: 'quiz',
      game_code: 30303,
      question_ids: ['q6', 'q7', 'q8'],
      is_active: true,
    },
    {
      _id: 'g4',
      creator_id: '63b2a2d45f7c6c1a4b5e4b62',
      title: 'History Buffs',
      maxUsers: 6,
      category: 'history',
      game_code: 40404,
      question_ids: ['q9', 'q10'],
      is_active: true,
    },
    {
      _id: 'g5',
      creator_id: '63b2a2d45f7c6c1a4b5e4b63',
      title: 'Word Wizard',
      maxUsers: 8,
      category: 'word games',
      game_code: 50505,
      question_ids: ['q11', 'q12'],
      is_active: true,
    },
    {
      _id: 'g6',
      creator_id: '63b2a2d45f7c6c1a4b5e4b64',
      title: 'Science Explorer',
      maxUsers: 10,
      category: 'science',
      game_code: 60606,
      question_ids: ['q13', 'q14', 'q15'],
      is_active: true,
    },
    {
      _id: 'g7',
      creator_id: '63b2a2d45f7c6c1a4b5e4b65',
      title: 'Trivia Night',
      maxUsers: 5,
      category: 'trivia',
      game_code: 70707,
      question_ids: ['q16', 'q17'],
      is_active: true,
    },
    {
      _id: 'g8',
      creator_id: '63b2a2d45f7c6c1a4b5e4b66',
      title: 'Math Marathon',
      maxUsers: 4,
      category: 'math',
      game_code: 80808,
      question_ids: ['q18', 'q19'],
      is_active: true,
    },
    {
      _id: 'g9',
      creator_id: '63b2a2d45f7c6c1a4b5e4b67',
      title: 'Quiz Quest',
      maxUsers: 3,
      category: 'quiz',
      game_code: 90909,
      question_ids: ['q20', 'q21', 'q22'],
      is_active: true,
    },
    {
      _id: 'g10',
      creator_id: '63b2a2d45f7c6c1a4b5e4b68',
      title: 'History Masters',
      maxUsers: 6,
      category: 'history',
      game_code: 10110,
      question_ids: ['q23', 'q24', 'q25'],
      is_active: true,
    },
    {
      _id: 'g11',
      creator_id: '63b2a2d45f7c6c1a4b5e4b69',
      title: 'Word Puzzles',
      maxUsers: 8,
      category: 'word games',
      game_code: 11111,
      question_ids: ['q26', 'q27'],
      is_active: true,
    },
    {
      _id: 'g12',
      creator_id: '63b2a2d45f7c6c1a4b5e4b70',
      title: 'Science Trivia',
      maxUsers: 10,
      category: 'science',
      game_code: 12121,
      question_ids: ['q28', 'q29', 'q30'],
      is_active: true,
    },
    {
      _id: 'g13',
      creator_id: '63b2a2d45f7c6c1a4b5e4b71',
      title: 'Trivia Frenzy',
      maxUsers: 5,
      category: 'trivia',
      game_code: 13131,
      question_ids: ['q31', 'q32'],
      is_active: true,
    },
    {
      _id: 'g14',
      creator_id: '63b2a2d45f7c6c1a4b5e4b72',
      title: 'Math Fun',
      maxUsers: 4,
      category: 'math',
      game_code: 14141,
      question_ids: ['q33', 'q34'],
      is_active: true,
    },
    {
      _id: 'g15',
      creator_id: '63b2a2d45f7c6c1a4b5e4b73',
      title: 'Ultimate Quiz',
      maxUsers: 3,
      category: 'quiz',
      game_code: 15151,
      question_ids: ['q35', 'q36', 'q37'],
      is_active: true,
    },
    {
      _id: 'g16',
      creator_id: '63b2a2d45f7c6c1a4b5e4b74',
      title: 'History Legends',
      maxUsers: 6,
      category: 'history',
      game_code: 16161,
      question_ids: ['q38', 'q39', 'q40'],
      is_active: true,
    },
    {
      _id: 'g17',
      creator_id: '63b2a2d45f7c6c1a4b5e4b75',
      title: 'Word Challenges',
      maxUsers: 8,
      category: 'word games',
      game_code: 17171,
      question_ids: ['q41', 'q42'],
      is_active: true,
    },
    {
      _id: 'g18',
      creator_id: '63b2a2d45f7c6c1a4b5e4b76',
      title: 'Science Wonders',
      maxUsers: 10,
      category: 'science',
      game_code: 18181,
      question_ids: ['q43', 'q44', 'q45'],
      is_active: true,
    },
    {
      _id: 'g19',
      creator_id: '63b2a2d45f7c6c1a4b5e4b77',
      title: 'Trivia Blast',
      maxUsers: 5,
      category: 'trivia',
      game_code: 19191,
      question_ids: ['q46', 'q47'],
      is_active: true,
    },
    {
      _id: 'g20',
      creator_id: '63b2a2d45f7c6c1a4b5e4b78',
      title: 'Math Mania',
      maxUsers: 4,
      category: 'math',
      game_code: 20202,
      question_ids: ['q48', 'q49', 'q50'],
      is_active: true,
    },
  ]);
  const categories = ref([
    'Trivia',
    'Math',
    'Quiz',
    'History',
    'Word Games',
    'Science',
  ]);

  function getGameById(gameId) {
    return games.value.find((g) => g._id === gameId);
  }

  function getGamesByCategory(category) {
    let filteredGames = [];
    filteredGames = games.value.filter(
      (game) => game.category === category.toLowerCase()
    );
    return filteredGames;
  }

  return {
    games,
    categories,
    getGameById,
    getGamesByCategory,
  };
});
