[
  {
    _id: 'q1',
    text: 'What is the capital of France?',
    timeLimit: 15,
    option: ['Paris', 'Berlin', 'Madrid', 'Rome'],
    correctOptionId: '0',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q2',
    text: "Who wrote 'Hamlet'?",
    timeLimit: 20,
    option: [
      'Charles Dickens',
      'William Shakespeare',
      'Jane Austen',
      'Leo Tolstoy',
    ],
    correctOptionId: '1',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q3',
    text: 'What is 2 + 2?',
    timeLimit: 10,
    option: ['3', '4', '5', '6'],
    correctOptionId: '1',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q4',
    text: 'What is the largest planet in our solar system?',
    timeLimit: 15,
    option: ['Earth', 'Mars', 'Jupiter', 'Saturn'],
    correctOptionId: '2',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q5',
    text: 'What year did World War II end?',
    timeLimit: 20,
    option: ['1940', '1945', '1950', '1960'],
    correctOptionId: '1',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q6',
    text: 'What does CPU stand for?',
    timeLimit: 15,
    option: [
      'Central Processing Unit',
      'Computer Processing Unit',
      'Central Programming Unit',
      'Core Processing Unit',
    ],
    correctOptionId: '0',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q7',
    text: 'Who is the founder of Microsoft?',
    timeLimit: 20,
    option: ['Steve Jobs', 'Bill Gates', 'Elon Musk', 'Mark Zuckerberg'],
    correctOptionId: '1',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q8',
    text: 'What does HTML stand for?',
    timeLimit: 15,
    option: [
      'HyperText Markup Language',
      'HighText Markup Language',
      'HyperTabular Markup Language',
      'None of these',
    ],
    correctOptionId: '0',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q9',
    text: 'What is the most popular programming language in 2023?',
    timeLimit: 20,
    option: ['Java', 'Python', 'C++', 'JavaScript'],
    correctOptionId: '1',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q10',
    text: 'What is 1024 bytes equal to?',
    timeLimit: 10,
    option: ['1 KB', '1 MB', '1 GB', '1 TB'],
    correctOptionId: '0',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q11',
    text: 'Which company developed the Linux operating system?',
    timeLimit: 15,
    option: ['Microsoft', 'Apple', 'Linus Torvalds', 'IBM'],
    correctOptionId: '2',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q12',
    text: 'What is the full form of HTTP?',
    timeLimit: 15,
    option: [
      'HyperText Transfer Protocol',
      'High Transfer Text Protocol',
      'HyperTool Transfer Protocol',
      'None of the above',
    ],
    correctOptionId: '0',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q13',
    text: 'What is the value of Pi to 3 decimal places?',
    timeLimit: 20,
    option: ['3.141', '3.142', '3.143', '3.144'],
    correctOptionId: '0',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q14',
    text: 'What is 12 x 12?',
    timeLimit: 10,
    option: ['142', '144', '148', '150'],
    correctOptionId: '1',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q15',
    text: 'What is the square root of 64?',
    timeLimit: 10,
    option: ['6', '8', '10', '12'],
    correctOptionId: '1',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q16',
    text: 'What is the area of a circle with radius 7? (Use Pi=3.14)',
    timeLimit: 20,
    option: ['154', '144', '134', '164'],
    correctOptionId: '0',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q17',
    text: 'What is 25% of 200?',
    timeLimit: 10,
    option: ['25', '50', '75', '100'],
    correctOptionId: '1',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q18',
    text: 'Solve: 5 + 3 x 2',
    timeLimit: 10,
    option: ['16', '11', '13', '10'],
    correctOptionId: '1',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q19',
    text: 'Convert 0.75 to a fraction.',
    timeLimit: 15,
    option: ['3/4', '1/2', '1/4', '2/3'],
    correctOptionId: '0',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q20',
    text: 'What is the value of 2^6?',
    timeLimit: 10,
    option: ['36', '64', '128', '256'],
    correctOptionId: '1',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q21',
    text: 'Who was the first President of the United States?',
    timeLimit: 15,
    option: [
      'Thomas Jefferson',
      'George Washington',
      'John Adams',
      'James Madison',
    ],
    correctOptionId: '1',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q22',
    text: 'In which year did the Titanic sink?',
    timeLimit: 20,
    option: ['1908', '1910', '1912', '1914'],
    correctOptionId: '2',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q23',
    text: 'Which ancient civilization built the pyramids?',
    timeLimit: 15,
    option: ['Greek', 'Roman', 'Egyptian', 'Mayan'],
    correctOptionId: '2',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q24',
    text: 'Who was known as the Iron Lady?',
    timeLimit: 15,
    option: [
      'Indira Gandhi',
      'Margaret Thatcher',
      'Angela Merkel',
      'Queen Elizabeth II',
    ],
    correctOptionId: '1',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q25',
    text: 'What year did World War I begin?',
    timeLimit: 20,
    option: ['1910', '1914', '1918', '1920'],
    correctOptionId: '1',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q26',
    text: 'Who was the first Emperor of Rome?',
    timeLimit: 20,
    option: ['Julius Caesar', 'Augustus', 'Nero', 'Caligula'],
    correctOptionId: '1',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q27',
    text: 'What is the chemical symbol for water?',
    timeLimit: 10,
    option: ['H2O', 'O2', 'CO2', 'NaCl'],
    correctOptionId: '0',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q28',
    text: 'What planet is known as the Red Planet?',
    timeLimit: 15,
    option: ['Earth', 'Venus', 'Mars', 'Jupiter'],
    correctOptionId: '2',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q29',
    text: 'What is the speed of light?',
    timeLimit: 20,
    option: ['300,000 km/s', '150,000 km/s', '1,000 km/s', '10,000 km/s'],
    correctOptionId: '0',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q30',
    text: 'What gas do plants absorb from the atmosphere?',
    timeLimit: 10,
    option: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Helium'],
    correctOptionId: '1',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q31',
    text: 'What is the boiling point of water?',
    timeLimit: 10,
    option: ['100°C', '0°C', '50°C', '200°C'],
    correctOptionId: '0',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q32',
    text: 'What is the largest continent?',
    timeLimit: 15,
    option: ['Africa', 'Asia', 'Europe', 'South America'],
    correctOptionId: '1',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q33',
    text: 'What country has the largest population?',
    timeLimit: 15,
    option: ['USA', 'India', 'China', 'Russia'],
    correctOptionId: '2',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q34',
    text: 'What is the longest river in the world?',
    timeLimit: 20,
    option: [
      'Amazon River',
      'Nile River',
      'Yangtze River',
      'Mississippi River',
    ],
    correctOptionId: '1',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q35',
    text: 'What is the smallest country in the world?',
    timeLimit: 15,
    option: ['Monaco', 'Vatican City', 'San Marino', 'Liechtenstein'],
    correctOptionId: '1',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q36',
    text: 'Which desert is the largest in the world?',
    timeLimit: 15,
    option: [
      'Sahara Desert',
      'Arctic Desert',
      'Gobi Desert',
      'Kalahari Desert',
    ],
    correctOptionId: '0',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q37',
    text: 'Which ocean is the largest?',
    timeLimit: 10,
    option: ['Atlantic Ocean', 'Indian Ocean', 'Pacific Ocean', 'Arctic Ocean'],
    correctOptionId: '2',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },

  {
    _id: 'q38',
    text: 'Which country won the FIFA World Cup in 2018?',
    timeLimit: 15,
    option: ['Brazil', 'Germany', 'France', 'Argentina'],
    correctOptionId: '2',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q39',
    text: 'What is the national sport of Japan?',
    timeLimit: 15,
    option: ['Baseball', 'Sumo Wrestling', 'Karate', 'Soccer'],
    correctOptionId: '1',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q40',
    text: "Which basketball player is known as 'His Airness'?",
    timeLimit: 15,
    option: [
      'Kobe Bryant',
      'LeBron James',
      'Michael Jordan',
      "Shaquille O'Neal",
    ],
    correctOptionId: '2',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q41',
    text: 'What is the maximum score in a single frame of bowling?',
    timeLimit: 10,
    option: ['100', '200', '300', '400'],
    correctOptionId: '2',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q42',
    text: 'How many players are there in a soccer team?',
    timeLimit: 10,
    option: ['9', '10', '11', '12'],
    correctOptionId: '2',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },

  {
    _id: 'q43',
    text: "Who directed the movie 'Inception'?",
    timeLimit: 15,
    option: [
      'Steven Spielberg',
      'Christopher Nolan',
      'James Cameron',
      'Quentin Tarantino',
    ],
    correctOptionId: '1',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q44',
    text: 'What is the highest-grossing film of all time?',
    timeLimit: 20,
    option: ['Avatar', 'Titanic', 'Avengers: Endgame', 'The Lion King'],
    correctOptionId: '0',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q45',
    text: "Which actor played the Joker in 'The Dark Knight'?",
    timeLimit: 15,
    option: ['Joaquin Phoenix', 'Jack Nicholson', 'Heath Ledger', 'Jared Leto'],
    correctOptionId: '2',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q46',
    text: "What is the name of the spaceship in 'Alien'?",
    timeLimit: 20,
    option: ['Nostromo', 'Enterprise', 'Millennium Falcon', 'Discovery One'],
    correctOptionId: '0',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q47',
    text: "Who played the titular character in the movie 'Forrest Gump'?",
    timeLimit: 15,
    option: [
      'Robin Wright',
      'Tom Hanks',
      'Gary Sinise',
      'Michael Clarke Duncan',
    ],
    correctOptionId: '1',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q48',
    text: "Who wrote 'Pride and Prejudice'?",
    timeLimit: 20,
    option: [
      'Jane Austen',
      'Charlotte Bronte',
      'Emily Dickinson',
      'Mary Shelley',
    ],
    correctOptionId: '0',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q49',
    text: 'What is the first book in the Harry Potter series?',
    timeLimit: 15,
    option: [
      "The Philosopher's Stone",
      'The Chamber of Secrets',
      'The Goblet of Fire',
      'The Prisoner of Azkaban',
    ],
    correctOptionId: '0',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q50',
    text: "Who wrote 'To Kill a Mockingbird'?",
    timeLimit: 15,
    option: ['Mark Twain', 'Harper Lee', 'Ernest Hemingway', 'John Steinbeck'],
    correctOptionId: '1',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q51',
    text: 'What is the title of the first Sherlock Holmes novel?',
    timeLimit: 20,
    option: [
      'The Hound of the Baskervilles',
      'A Study in Scarlet',
      'The Sign of Four',
      'The Valley of Fear',
    ],
    correctOptionId: '1',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q52',
    text: "Who wrote '1984'?",
    timeLimit: 15,
    option: [
      'Aldous Huxley',
      'George Orwell',
      'Ray Bradbury',
      'Philip K. Dick',
    ],
    correctOptionId: '1',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q53',
    text: "Who is known as the 'King of Pop'?",
    timeLimit: 10,
    option: ['Elvis Presley', 'Michael Jackson', 'Prince', 'Stevie Wonder'],
    correctOptionId: '1',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q54',
    text: "Which band released the album 'Abbey Road'?",
    timeLimit: 15,
    option: ['The Beatles', 'The Rolling Stones', 'Pink Floyd', 'Led Zeppelin'],
    correctOptionId: '0',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q55',
    text: "Who composed the 'Four Seasons'?",
    timeLimit: 15,
    option: [
      'Ludwig van Beethoven',
      'Johann Sebastian Bach',
      'Antonio Vivaldi',
      'Wolfgang Amadeus Mozart',
    ],
    correctOptionId: '2',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q56',
    text: 'What year did Elvis Presley die?',
    timeLimit: 15,
    option: ['1977', '1980', '1975', '1985'],
    correctOptionId: '0',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q57',
    text: 'What is the best-selling album of all time?',
    timeLimit: 15,
    option: ['Thriller', 'Back in Black', 'Dark Side of the Moon', 'The Wall'],
    correctOptionId: '0',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },

  {
    _id: 'q58',
    text: 'Who painted the Mona Lisa?',
    timeLimit: 15,
    option: [
      'Leonardo da Vinci',
      'Vincent van Gogh',
      'Pablo Picasso',
      'Claude Monet',
    ],
    correctOptionId: '0',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q59',
    text: 'What is the art movement started by Picasso and Braque?',
    timeLimit: 20,
    option: ['Cubism', 'Surrealism', 'Impressionism', 'Expressionism'],
    correctOptionId: '0',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q60',
    text: "Which artist is famous for the painting 'The Starry Night'?",
    timeLimit: 15,
    option: [
      'Claude Monet',
      'Vincent van Gogh',
      'Paul Gauguin',
      'Salvador Dalí',
    ],
    correctOptionId: '1',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q61',
    text: 'What medium did Michelangelo use for the Sistine Chapel ceiling?',
    timeLimit: 20,
    option: ['Oil Paint', 'Tempera', 'Fresco', 'Acrylic'],
    correctOptionId: '2',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q62',
    text: "What is the name of the artist who created 'The Persistence of Memory'?",
    timeLimit: 15,
    option: ['Salvador Dalí', 'Henri Matisse', 'René Magritte', 'Joan Miró'],
    correctOptionId: '0',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q63',
    text: 'What is the formula for force?',
    timeLimit: 15,
    option: ['F=ma', 'E=mc^2', 'P=IV', 'V=IR'],
    correctOptionId: '0',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q64',
    text: 'Who discovered the law of gravitation?',
    timeLimit: 15,
    option: [
      'Albert Einstein',
      'Isaac Newton',
      'Galileo Galilei',
      'Niels Bohr',
    ],
    correctOptionId: '1',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q65',
    text: "What particle is known as the 'God Particle'?",
    timeLimit: 20,
    option: ['Proton', 'Neutron', 'Electron', 'Higgs Boson'],
    correctOptionId: '3',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q66',
    text: 'What is the speed of sound in air?',
    timeLimit: 15,
    option: ['300 m/s', '340 m/s', '500 m/s', '600 m/s'],
    correctOptionId: '1',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q67',
    text: 'What is the unit of resistance?',
    timeLimit: 10,
    option: ['Volt', 'Ohm', 'Watt', 'Ampere'],
    correctOptionId: '1',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q68',
    text: 'What is the chemical symbol for gold?',
    timeLimit: 10,
    option: ['Ag', 'Au', 'Pb', 'Pt'],
    correctOptionId: '1',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q69',
    text: 'What is the pH of pure water?',
    timeLimit: 15,
    option: ['5', '7', '9', '11'],
    correctOptionId: '1',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q70',
    text: "Which element is known as the 'King of Chemicals'?",
    timeLimit: 20,
    option: ['Hydrogen', 'Oxygen', 'Sulfur', 'Nitrogen'],
    correctOptionId: '2',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q71',
    text: 'What is the formula for table salt?',
    timeLimit: 10,
    option: ['NaCl', 'KCl', 'MgCl', 'CaCl'],
    correctOptionId: '0',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q72',
    text: 'Which gas is produced when metals react with acids?',
    timeLimit: 15,
    option: ['Oxygen', 'Hydrogen', 'Carbon Dioxide', 'Nitrogen'],
    correctOptionId: '1',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q73',
    text: 'What is the closest planet to the Sun?',
    timeLimit: 10,
    option: ['Venus', 'Mercury', 'Mars', 'Earth'],
    correctOptionId: '1',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q74',
    text: 'What is the name of the galaxy we live in?',
    timeLimit: 15,
    option: ['Andromeda', 'Milky Way', 'Triangulum', 'Whirlpool'],
    correctOptionId: '1',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q75',
    text: "What is the name of Saturn's largest moon?",
    timeLimit: 15,
    option: ['Titan', 'Europa', 'Io', 'Ganymede'],
    correctOptionId: '0',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q76',
    text: 'What is the term for a star that suddenly increases in brightness?',
    timeLimit: 20,
    option: ['Nova', 'Supernova', 'Quasar', 'Pulsar'],
    correctOptionId: '0',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q77',
    text: "Which planet is known as the 'Red Planet'?",
    timeLimit: 10,
    option: ['Venus', 'Mars', 'Jupiter', 'Saturn'],
    correctOptionId: '1',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q78',
    text: 'What is the powerhouse of the cell?',
    timeLimit: 10,
    option: ['Nucleus', 'Ribosome', 'Mitochondria', 'Golgi Apparatus'],
    correctOptionId: '2',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q79',
    text: 'What is the process by which plants make food?',
    timeLimit: 15,
    option: ['Respiration', 'Photosynthesis', 'Fermentation', 'Digestion'],
    correctOptionId: '1',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q80',
    text: 'What is the largest organ in the human body?',
    timeLimit: 15,
    option: ['Heart', 'Liver', 'Skin', 'Lungs'],
    correctOptionId: '2',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q81',
    text: 'What is the genetic material in cells?',
    timeLimit: 20,
    option: ['RNA', 'DNA', 'Protein', 'Carbohydrates'],
    correctOptionId: '1',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q82',
    text: 'What is the smallest unit of life?',
    timeLimit: 15,
    option: ['Atom', 'Cell', 'Molecule', 'Organ'],
    correctOptionId: '1',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q83',
    text: 'Who was the first president of the United States?',
    timeLimit: 15,
    option: [
      'John Adams',
      'Thomas Jefferson',
      'George Washington',
      'James Madison',
    ],
    correctOptionId: '2',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q84',
    text: 'Who discovered penicillin?',
    timeLimit: 20,
    option: [
      'Marie Curie',
      'Alexander Fleming',
      'Louis Pasteur',
      'Edward Jenner',
    ],
    correctOptionId: '1',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q85',
    text: 'Who was the leader of Nazi Germany during World War II?',
    timeLimit: 15,
    option: [
      'Adolf Hitler',
      'Joseph Stalin',
      'Benito Mussolini',
      'Winston Churchill',
    ],
    correctOptionId: '0',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q86',
    text: 'Who was the first woman to win a Nobel Prize?',
    timeLimit: 20,
    option: [
      'Marie Curie',
      'Rosalind Franklin',
      'Ada Lovelace',
      'Florence Nightingale',
    ],
    correctOptionId: '0',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q87',
    text: 'Who was the 16th president of the United States?',
    timeLimit: 15,
    option: [
      'James Buchanan',
      'Abraham Lincoln',
      'Andrew Johnson',
      'Ulysses S. Grant',
    ],
    correctOptionId: '1',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q88',
    text: 'What is the capital of Japan?',
    timeLimit: 10,
    option: ['Osaka', 'Tokyo', 'Kyoto', 'Nagoya'],
    correctOptionId: '1',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q89',
    text: 'What is the capital of Canada?',
    timeLimit: 15,
    option: ['Toronto', 'Ottawa', 'Vancouver', 'Montreal'],
    correctOptionId: '1',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q90',
    text: 'What is the capital of Australia?',
    timeLimit: 15,
    option: ['Sydney', 'Melbourne', 'Canberra', 'Brisbane'],
    correctOptionId: '2',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q91',
    text: 'What is the capital of South Africa?',
    timeLimit: 20,
    option: ['Cape Town', 'Pretoria', 'Bloemfontein', 'All of the above'],
    correctOptionId: '3',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q92',
    text: 'What is the capital of Brazil?',
    timeLimit: 10,
    option: ['Rio de Janeiro', 'Brasilia', 'Sao Paulo', 'Salvador'],
    correctOptionId: '1',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q93',
    text: 'Who founded Amazon?',
    timeLimit: 10,
    option: ['Elon Musk', 'Jeff Bezos', 'Bill Gates', 'Larry Page'],
    correctOptionId: '1',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q94',
    text: 'Who is the CEO of Tesla?',
    timeLimit: 10,
    option: ['Elon Musk', 'Jeff Bezos', 'Tim Cook', 'Sundar Pichai'],
    correctOptionId: '0',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q95',
    text: 'Which company developed the iPhone?',
    timeLimit: 10,
    option: ['Samsung', 'Apple', 'Nokia', 'Sony'],
    correctOptionId: '1',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q96',
    text: 'Who co-founded Microsoft?',
    timeLimit: 15,
    option: ['Paul Allen', 'Bill Gates', 'Both', 'None'],
    correctOptionId: '2',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q97',
    text: 'What year was Google founded?',
    timeLimit: 15,
    option: ['1995', '1996', '1997', '1998'],
    correctOptionId: '3',
    creator_id: '677fd15a50a8a7c49bf5c4bc',
  },
  {
    _id: 'q98',
    text: 'Which language is known as the language of the web?',
    timeLimit: 10,
    option: ['Python', 'JavaScript', 'Java', 'C++'],
    correctOptionId: '1',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q99',
    text: 'What is the most popular programming language in 2023?',
    timeLimit: 10,
    option: ['Java', 'Python', 'C++', 'JavaScript'],
    correctOptionId: '1',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q100',
    text: 'What does HTML stand for?',
    timeLimit: 15,
    option: [
      'HyperText Markup Language',
      'HyperTabular Markup Language',
      'HighText Markup Language',
      'None of the above',
    ],
    correctOptionId: '0',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q101',
    text: 'Which company developed the Java programming language?',
    timeLimit: 15,
    option: ['Microsoft', 'Apple', 'Sun Microsystems', 'IBM'],
    correctOptionId: '2',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q102',
    text: 'Which programming language is used for developing iOS apps?',
    timeLimit: 15,
    option: ['Swift', 'Kotlin', 'Objective-C', 'Both A and C'],
    correctOptionId: '3',
    creator_id: '677fd12950a8a7c49bf5c4b6',
  },
  {
    _id: 'q103',
    text: 'Who is the king of the Greek gods?',
    timeLimit: 10,
    option: ['Zeus', 'Poseidon', 'Hades', 'Apollo'],
    correctOptionId: '0',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q104',
    text: "In Norse mythology, what is the name of Thor's hammer?",
    timeLimit: 15,
    option: ['Mjolnir', 'Gungnir', 'Stormbreaker', 'Excalibur'],
    correctOptionId: '0',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q105',
    text: 'Who is the Egyptian god of the sun?',
    timeLimit: 10,
    option: ['Osiris', 'Ra', 'Anubis', 'Horus'],
    correctOptionId: '1',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q106',
    text: 'What is the Roman name for the Greek god Hermes?',
    timeLimit: 15,
    option: ['Mercury', 'Mars', 'Apollo', 'Jupiter'],
    correctOptionId: '0',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
  {
    _id: 'q107',
    text: 'In Hindu mythology, who is the preserver of the universe?',
    timeLimit: 15,
    option: ['Shiva', 'Vishnu', 'Brahma', 'Indra'],
    correctOptionId: '1',
    creator_id: '677fd14350a8a7c49bf5c4b9',
  },
];
